name: WTFLess
description: for you code
meta_description: "WTFLess for your code, for a cleaner code ;)"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'http://wtfless.github.io'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'wtfless.githud.i2o'
author:         'Henrique Westphal'
author2:         'Jonathan Beber'
